### ISSUE TITLE
Non rails apps

### ISSUE THREAD

**Issue by alexandru-calinoiu** [igorkasyanchuk/fake_api#1]
Hi,

Very cool gem, was wondering if you have any plans to make this work without rails, in plain rack apps?

**Comment by igorkasyanchuk** [comment]
Here is a very simple version:

https://github.com/igorkasyanchuk/fake_api#standalone-mode-1

PS: it runs inside blank Rails app, but no need to attach to existing

**Comment by igorkasyanchuk** [comment]
it was added in new version 0.9.1
